"""
Quick Dialogue Timestamp Mapper
Simplified version with better error handling and dependency checking
Now supports reading script files generated by script_generation.py
"""

import json
from pathlib import Path
import logging
import argparse
import re
from difflib import SequenceMatcher

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def seconds_to_mmss(seconds):
    """Convert seconds to MM:SS format"""
    # Handle negative durations
    if seconds < 0:
        return f"-{seconds_to_mmss(abs(seconds))}"

    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{minutes:02d}:{secs:02d}"

def calculate_similarity(text1, text2):
    """Calculate similarity ratio between two texts"""
    return SequenceMatcher(None, text1.lower(), text2.lower()).ratio()

def find_text_differences(script_text, recognized_text):
    """
    Find differences between script text and recognized text
    Returns list of mismatched word indices and similarity score
    """
    script_words = script_text.lower().split()
    recognized_words = recognized_text.lower().split()

    mismatches = []
    similarity = calculate_similarity(script_text, recognized_text)

    # Simple word-by-word comparison (works best when word counts are similar)
    max_len = max(len(script_words), len(recognized_words))
    for i in range(max_len):
        script_word = script_words[i] if i < len(script_words) else ""
        recognized_word = recognized_words[i] if i < len(recognized_words) else ""

        if script_word != recognized_word:
            mismatches.append({
                "position": i,
                "expected": script_word,
                "recognized": recognized_word
            })

    return mismatches, similarity

def check_dependencies():
    """Check if required dependencies are available"""
    missing_deps = []

    try:
        import whisperx
        logger.info("✅ WhisperX available")
    except ImportError:
        missing_deps.append("whisperx")

    try:
        import librosa
        logger.info("✅ librosa available")
    except ImportError:
        missing_deps.append("librosa")

    if missing_deps:
        logger.error(f"❌ Missing dependencies: {missing_deps}")
        logger.info("Install with: pip install whisperx librosa")
        return False

    return True

def parse_generated_script(script_path):
    """
    Parse script file generated by script_generation.py

    Expected format:
        A: dialogue text here
        B: dialogue text here
    Or:
        Name1: dialogue text here
        Name2: dialogue text here

    Returns list of {"speaker": "A/B", "text": "dialogue text"}
    """
    logger.info(f"📖 Reading script from: {script_path}")

    if not Path(script_path).exists():
        logger.error(f"❌ Script file not found: {script_path}")
        return None

    with open(script_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find where the actual dialogue starts (after the header)
    lines = content.split('\n')

    dialogues = []
    dialogue_started = False
    speaker_map = {}  # Maps actual names to A/B labels
    next_speaker_label = 'A'

    for line in lines:
        line = line.strip()

        # Skip empty lines
        if not line:
            continue

        # Skip header lines until we find the separator
        if '=' * 10 in line:
            dialogue_started = True
            continue

        # Parse dialogue lines: "Name: dialogue text" with flexible speaker names
        match = re.match(r'^([A-Za-z\u0900-\u097F]+):\s*(.+)$', line)
        if match:
            # If we found a dialogue line, we can assume the dialogue has started
            # This handles scripts sent directly without separator lines
            dialogue_started = True

            speaker_name = match.group(1)
            text = match.group(2).strip()

            # Skip empty text
            if not text:
                continue

            # Map speaker name to A or B
            if speaker_name not in speaker_map:
                if next_speaker_label == 'A':
                    speaker_map[speaker_name] = 'A'
                    next_speaker_label = 'B'
                    logger.info(f"   Mapped '{speaker_name}' → Speaker A")
                elif next_speaker_label == 'B':
                    speaker_map[speaker_name] = 'B'
                    next_speaker_label = 'done'
                    logger.info(f"   Mapped '{speaker_name}' → Speaker B")
                else:
                    # More than 2 speakers detected - use the first mapping found
                    logger.warning(f"⚠️  More than 2 speakers detected. '{speaker_name}' will be mapped to previous speaker.")
                    # Map to the closest previous speaker (could be improved with better logic)
                    speaker_map[speaker_name] = 'A'

            speaker_label = speaker_map[speaker_name]

            dialogues.append({
                "speaker": speaker_label,
                "text": text
            })
        elif not dialogue_started:
            # Skip configuration/header lines before dialogue starts
            continue

    if not dialogues:
        logger.error("❌ No dialogues found in script!")
        logger.error("Make sure the script has lines with format 'Name: dialogue text'")
        logger.error("Examples: 'A: hello' or 'Kalyani: hello' or 'John: hello'")
        return None

    logger.info(f"✅ Loaded {len(dialogues)} dialogue lines from script")
    logger.info(f"   Speaker A: {len([d for d in dialogues if d['speaker'] == 'A'])} lines")
    logger.info(f"   Speaker B: {len([d for d in dialogues if d['speaker'] == 'B'])} lines")

    return dialogues

def map_dialogue_timestamps(script_path=None, merged_audio_path=None, output_json_path=None, language="hi", save_transcript=True):
    """
    Main function to map dialogue to timestamps

    Args:
        script_path: Path to generated script file (optional, uses default example if not provided)
        merged_audio_path: Path to merged audio WAV file
        output_json_path: Path for output JSON (optional)
        language: Language code for alignment (default: "hi" for Hindi)
        save_transcript: Whether to save the WhisperX-generated transcript (default: True)

    Returns:
        Dictionary with 'timestamps' and 'transcript_path' keys, or None on error
    """

    # Check dependencies first
    if not check_dependencies():
        return None

    import whisperx
    import librosa

    # Load dialogue script
    if script_path:
        dialogue_script = parse_generated_script(script_path)
        if not dialogue_script:
            return None
    else:
        # Fallback to hardcoded example
        logger.info("ℹ️  No script file provided, using default example")
        dialogue_script = [
            {"speaker": "A", "text": "मुझे एयरपोर्ट जाना है"},
            {"speaker": "B", "text": "कौन से एयरपोर्ट"},
            {"speaker": "A", "text": "इंदिरा गांधी अंतर्राष्ट्रीय एयरपोर्ट।"},
            {"speaker": "B", "text": "आप कहां से पिकअप चाहती हैं?"},
            {"speaker": "A", "text": "राजौरी गार्डन से।"},
            {"speaker": "B", "text": "कैब पंद्रह मिनट में आ जाएगी।"},
        ]

    # File paths - USE MERGED AUDIO FOR TIMING
    if merged_audio_path:
        merged_audio = merged_audio_path
    else:
        # Default paths for backward compatibility
        base_path = Path(__file__).parent / "Speaker separated" / "Hindi"
        merged_audio = str(base_path / "MH_25.wav")  # The full conversation for timing

    # Output path
    if output_json_path:
        output_json = output_json_path
    else:
        # Auto-generate output name based on script or use default
        if script_path:
            script_name = Path(script_path).stem
            output_json = str(Path(__file__).parent / f"{script_name}_timestamps.json")
        else:
            output_json = str(Path(__file__).parent / "01_dialogue.json")
    
    # Check if merged audio exists
    if not Path(merged_audio).exists():
        logger.error(f"❌ Audio file not found: {merged_audio}")
        return None

    logger.info(f"📁 Merged audio: {merged_audio}")
    logger.info(f"📁 Output JSON: {output_json}")
    
    try:
        # Device settings
        device = "cpu"

        logger.info(f"🔄 Loading {language} alignment model...")
        model, metadata = whisperx.load_align_model(language_code=language, device=device)
        logger.info("✅ Model loaded successfully")
        
        # Load the MERGED conversation audio for accurate timing
        logger.info("\n🎤 Loading merged conversation audio...")
        merged_audio_data = whisperx.load_audio(merged_audio)
        duration = librosa.get_duration(y=merged_audio_data, sr=16000)
        logger.info(f"📊 Total conversation duration: {duration:.2f} seconds")
        
        # Combine ALL dialogue text in conversation order
        full_conversation_text = " ".join([line['text'] for line in dialogue_script])
        logger.info(f"📝 Full conversation text: {len(full_conversation_text)} chars")

        # For very long audio, process in chunks to avoid memory issues
        # WhisperX can handle about 5-10 minutes comfortably
        MAX_CHUNK_DURATION = 300  # 5 minutes per chunk
        all_words = []

        if duration > MAX_CHUNK_DURATION:
            logger.info(f"⚠️  Long audio detected ({duration:.1f}s). Processing in chunks...")

            # Calculate number of chunks needed
            num_chunks = int(duration / MAX_CHUNK_DURATION) + 1
            chunk_duration = duration / num_chunks

            logger.info(f"   Splitting into {num_chunks} chunks of ~{chunk_duration:.1f}s each")

            # Estimate words per chunk based on total text length
            total_words = len(full_conversation_text.split())
            words_per_second = total_words / duration

            for chunk_idx in range(num_chunks):
                chunk_start = chunk_idx * chunk_duration
                chunk_end = min((chunk_idx + 1) * chunk_duration, duration)

                logger.info(f"\n   📦 Processing chunk {chunk_idx + 1}/{num_chunks} ({chunk_start:.1f}s - {chunk_end:.1f}s)...")

                # Extract audio chunk
                start_sample = int(chunk_start * 16000)
                end_sample = int(chunk_end * 16000)
                chunk_audio = merged_audio_data[start_sample:end_sample]

                # Estimate text for this chunk
                start_word_idx = int(chunk_start * words_per_second)
                end_word_idx = int(chunk_end * words_per_second)
                chunk_words = full_conversation_text.split()[start_word_idx:end_word_idx]
                chunk_text = " ".join(chunk_words)

                if not chunk_text.strip():
                    logger.warning(f"   ⚠️  Empty text for chunk {chunk_idx + 1}, skipping")
                    continue

                # Create segment for this chunk
                chunk_segments = [{
                    "text": chunk_text,
                    "start": 0.0,
                    "end": chunk_end - chunk_start
                }]

                # Align this chunk
                try:
                    chunk_result = whisperx.align(chunk_segments, model, metadata, chunk_audio, device=device)

                    # Extract words and adjust timestamps to absolute time
                    for segment in chunk_result["segments"]:
                        if "words" in segment:
                            for word in segment["words"]:
                                # Adjust timestamps to absolute audio time
                                word["start"] = word.get("start", 0.0) + chunk_start
                                word["end"] = word.get("end", 0.0) + chunk_start
                                all_words.append(word)

                    logger.info(f"   ✅ Chunk {chunk_idx + 1} aligned ({len(chunk_result.get('segments', [{}])[0].get('words', []))} words)")

                except Exception as e:
                    logger.error(f"   ❌ Error aligning chunk {chunk_idx + 1}: {e}")
                    # Continue with next chunk instead of failing completely
                    continue

            logger.info(f"\n✅ All chunks processed. Total aligned words: {len(all_words)}")

        else:
            # Original code for shorter audio
            # Create segment for the entire conversation
            segments = [{
                "text": full_conversation_text,
                "start": 0.0,
                "end": duration
            }]

            # Perform forced alignment on the FULL conversation
            logger.info("🔄 Aligning full conversation...")
            result = whisperx.align(segments, model, metadata, merged_audio_data, device=device)

            # Extract all words with timestamps from the merged audio
            for segment in result["segments"]:
                if "words" in segment:
                    all_words.extend(segment["words"])

            logger.info(f"✅ Aligned {len(all_words)} words from merged audio")

        if not all_words:
            logger.error("❌ No words were aligned!")
            return None

        # Map words back to individual dialogue lines
        all_results = []
        transcript_lines = []  # Line-by-line transcript with speaker info
        word_idx = 0
        
        for idx, dialogue in enumerate(dialogue_script):
            dialogue_text = dialogue['text'].strip()
            dialogue_words = dialogue_text.split()
            n_words = len(dialogue_words)
            
            if n_words == 0:
                logger.warning(f"⚠️  Empty dialogue at index {idx + 1}")
                continue
            
            if word_idx >= len(all_words):
                logger.warning(f"⚠️  Ran out of words at dialogue {idx + 1}")
                break
            
            # Get the words for this dialogue line
            end_word_idx = min(word_idx + n_words - 1, len(all_words) - 1)

            # Find valid start time (some words may not have timestamps)
            start_time = None
            for i in range(word_idx, min(word_idx + n_words, len(all_words))):
                if "start" in all_words[i] and all_words[i]["start"] is not None:
                    start_time = all_words[i]["start"]
                    break

            # If no valid start time found, estimate from previous dialogue
            if start_time is None:
                if idx > 0 and len(all_results) > 0:
                    # Use end time of previous dialogue
                    start_time = all_results[-1]["end_time_seconds"] + 0.5
                    logger.warning(f"⚠️  No start timestamp for dialogue {idx + 1}, estimated from previous: {start_time:.2f}s")
                else:
                    start_time = 0.0
                    logger.warning(f"⚠️  No start timestamp for dialogue {idx + 1}, using 0.0")

            # Find valid end time
            end_time = None
            for i in range(end_word_idx, word_idx - 1, -1):  # Search backwards
                if i < len(all_words) and "end" in all_words[i] and all_words[i]["end"] is not None:
                    end_time = all_words[i]["end"]
                    break

            # If no valid end time found, estimate
            if end_time is None or end_time <= start_time:
                # Estimate based on average speaking rate (150 words per minute = 2.5 words per second)
                estimated_duration = n_words / 2.5
                end_time = start_time + estimated_duration
                logger.warning(f"⚠️  No valid end timestamp for dialogue {idx + 1}, estimated duration: {estimated_duration:.2f}s")

            # Collect the actual words recognized by WhisperX for this line
            recognized_words = []
            avg_score = 0.0
            score_count = 0
            for i in range(word_idx, min(word_idx + n_words, len(all_words))):
                word_info = all_words[i]
                recognized_words.append(word_info.get("word", ""))
                if "score" in word_info:
                    avg_score += word_info.get("score", 0.0)
                    score_count += 1

            # Calculate average confidence score for this line
            if score_count > 0:
                avg_score = avg_score / score_count
            else:
                avg_score = 0.0

            recognized_text = " ".join(recognized_words).strip()

            # Validation: Check for issues
            timestamp_estimated = False
            if end_time <= start_time:
                logger.error(f"❌ Invalid timestamps for dialogue {idx + 1}: start={start_time:.2f}, end={end_time:.2f}")
                end_time = start_time + 1.0  # Force minimum 1 second duration
                timestamp_estimated = True

            result_entry = {
                "index": idx + 1,
                "speaker": dialogue['speaker'],
                "start_time": seconds_to_mmss(start_time),
                "start_time_seconds": round(start_time, 2),
                "end_time": seconds_to_mmss(end_time),
                "end_time_seconds": round(end_time, 2),
                "duration": seconds_to_mmss(end_time - start_time),
                "text": dialogue_text
            }

            # Mark if timestamps were estimated
            if timestamp_estimated:
                result_entry["timestamp_estimated"] = True

            all_results.append(result_entry)

            # Find differences between script and recognized text
            mismatches, similarity = find_text_differences(dialogue_text, recognized_text)

            # Determine if this line has issues
            has_issues = similarity < 0.8 or len(mismatches) > 0 or timestamp_estimated

            # Build line-by-line transcript entry
            transcript_entry = {
                "index": idx + 1,
                "speaker": dialogue['speaker'],
                "start_time": seconds_to_mmss(start_time),
                "start_time_seconds": round(start_time, 2),
                "end_time": seconds_to_mmss(end_time),
                "end_time_seconds": round(end_time, 2),
                "duration": seconds_to_mmss(end_time - start_time),
                "script_text": dialogue_text,
                "recognized_text": recognized_text,
                "confidence": round(avg_score, 3),
                "similarity": round(similarity, 3),
                "has_issues": has_issues
            }

            # Mark if timestamps were estimated
            if timestamp_estimated:
                transcript_entry["timestamp_estimated"] = True
                transcript_entry["warning"] = "Timestamps were estimated due to missing or invalid data from alignment"

            # Add mismatch details if there are differences
            if mismatches:
                transcript_entry["mismatches"] = mismatches
                transcript_entry["mismatch_count"] = len(mismatches)

            transcript_lines.append(transcript_entry)

            logger.info(f"  {idx + 1:2d}. [{start_time:6.2f}s - {end_time:6.2f}s] "
                       f"{dialogue['speaker']}: {dialogue_text[:50]}...")

            word_idx += n_words
        
        # Save timestamps to JSON
        with open(output_json, 'w', encoding='utf-8') as f:
            json.dump(all_results, f, ensure_ascii=False, indent=2)

        logger.info(f"\n✅ SUCCESS: Corrected timestamps saved to {output_json}")

        # Save WhisperX transcript if requested
        transcript_path = None
        if save_transcript:
            transcript_path = output_json.replace('_timestamps.json', '_transcript.json')
            if transcript_path == output_json:  # Fallback if pattern doesn't match
                transcript_path = output_json.replace('.json', '_transcript.json')

            # Calculate overall statistics
            total_confidence = sum(line["confidence"] for line in transcript_lines) / len(transcript_lines) if transcript_lines else 0.0
            average_similarity = sum(line["similarity"] for line in transcript_lines) / len(transcript_lines) if transcript_lines else 0.0
            lines_with_issues = sum(1 for line in transcript_lines if line.get("has_issues", False))
            total_mismatches = sum(line.get("mismatch_count", 0) for line in transcript_lines)

            transcript_data = {
                "metadata": {
                    "total_lines": len(transcript_lines),
                    "duration_seconds": duration,
                    "duration_formatted": seconds_to_mmss(duration),
                    "language": language,
                    "average_confidence": round(total_confidence, 3),
                    "average_similarity": round(average_similarity, 3),
                    "lines_with_issues": lines_with_issues,
                    "total_mismatches": total_mismatches,
                    "quality_status": "excellent" if average_similarity > 0.9 else "good" if average_similarity > 0.8 else "needs_review",
                    "note": "Compare 'script_text' (your original script) with 'recognized_text' (what WhisperX detected). Lines with 'has_issues: true' have low similarity or mismatches."
                },
                "transcript": transcript_lines
            }

            with open(transcript_path, 'w', encoding='utf-8') as f:
                json.dump(transcript_data, f, ensure_ascii=False, indent=2)

            logger.info(f"✅ WhisperX transcript saved to {transcript_path}")
            logger.info(f"   Average confidence: {total_confidence:.3f}")

        # Display results
        logger.info("\n📋 CORRECTED TIMELINE:")
        for item in all_results:
            logger.info(f"{item['index']:2d}. [{item['start_time']} - {item['end_time']}] "
                       f"({item['duration']}) {item['speaker']}: {item['text'][:60]}...")

        # Validate no overlaps (use seconds for comparison)
        logger.info("\n🔍 VALIDATION:")
        overlaps = []
        for i in range(len(all_results) - 1):
            current = all_results[i]
            next_item = all_results[i + 1]
            if current['end_time_seconds'] > next_item['start_time_seconds']:
                overlaps.append((current['index'], next_item['index']))

        if overlaps:
            logger.warning(f"⚠️  Found {len(overlaps)} overlaps: {overlaps}")
        else:
            logger.info("✅ No overlaps detected - timeline is sequential!")

        # Return both timestamps and transcript path
        return {
            "timestamps": all_results,
            "transcript_path": transcript_path
        }
        
    except Exception as e:
        logger.error(f"❌ Error during processing: {e}")
        import traceback
        traceback.print_exc()
        return None

if __name__ == "__main__":
    # Parse command line arguments
    parser = argparse.ArgumentParser(
        description="Map dialogue script to audio timestamps using WhisperX",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Use default example (hardcoded script)
  python quick_mapper.py

  # Map generated script to audio
  python quick_mapper.py --script script_health_insurance_frustrated_9000words.txt --audio merged_audio.wav

  # Specify custom output path
  python quick_mapper.py --script my_script.txt --audio my_audio.wav --output timestamps.json

  # Use different language (e.g., English)
  python quick_mapper.py --script english_script.txt --audio audio.wav --language en
        """
    )

    parser.add_argument("--script", type=str, default=None,
                        help="Path to generated script file (A: and B: format)")

    parser.add_argument("--audio", type=str, default=None,
                        help="Path to merged audio WAV file")

    parser.add_argument("--output", type=str, default=None,
                        help="Path for output JSON file (auto-generated if not provided)")

    parser.add_argument("--language", type=str, default="hi",
                        help="Language code for alignment (hi=Hindi, en=English, etc.)")

    args = parser.parse_args()

    logger.info("🚀 Starting Dialogue Timestamp Mapper")
    logger.info("🎯 Using merged audio for accurate timing")
    logger.info("=" * 60)

    result = map_dialogue_timestamps(
        script_path=args.script,
        merged_audio_path=args.audio,
        output_json_path=args.output,
        language=args.language
    )

    if result:
        timestamps = result.get('timestamps', result if isinstance(result, list) else [])
        transcript_path = result.get('transcript_path') if isinstance(result, dict) else None

        logger.info(f"\n🎉 Successfully mapped {len(timestamps)} dialogues!")

        # Show statistics
        total_duration = max(item['end_time'] for item in timestamps) if timestamps else 0
        speaker_a_count = len([x for x in timestamps if x['speaker'] == 'A'])
        speaker_b_count = len([x for x in timestamps if x['speaker'] == 'B'])

        logger.info(f"\n📊 STATISTICS:")
        logger.info(f"   Total duration: {total_duration:.2f} seconds")
        logger.info(f"   Speaker A: {speaker_a_count} dialogues")
        logger.info(f"   Speaker B: {speaker_b_count} dialogues")

        if transcript_path:
            logger.info(f"   WhisperX transcript: {transcript_path}")
    else:
        logger.error("\n❌ Mapping failed. Please check the logs above.")